config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :homes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create] do
      member do
        get '/pending', to: 'bookings#pending', as: :pending
        get '/approve', to: 'bookings#approve', as: :approve
        get '/reject', to: 'bookings#reject', as: :reject
      end
    end
    member do
      get '/bookings', to: 'bookings#home_bookings', as: :home_bookings
    end
    resources :notes, only: [:index, :new, :create]
    resources :ownerships, only: [:index]
  end
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :users, only: [:show]
  resources :notes, only: [:index, :new, :create, :destroy]
  resources :ownerships, only: [:edit, :update]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :home

  validates :start_date, :end_date, :no_of_guest, presence: true
  validates :end_date, date: { after_or_equal_to: :start_date }
  validates :no_of_guest, numericality: { greater_than_or_equal_to: 0 }
  validates :status, inclusion: { in: %w[Confirmed Pending Rejected] }

  def ownership
    Ownership.find_by(user: user, home: home)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update, :destroy]

  def index
    @bookings = policy_scope(Booking).includes(:user).where(user: current_user)
    @booking = edit

    @homes = Home.geocoded
    # gives us all the homes which the current users have the bookings
    @homes = @homes.joins(:bookings, :users).where("bookings.user_id = #{current_user.id}")
    @markers = @homes.map do |home|
      {
        lat: home.latitude,
        lng: home.longitude
      }
    end
  end

  def home_bookings
    @home = Home.find(params[:id])
    authorize @home, :show?
    @bookings = @home.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @home = Home.find(params[:home_id])
    @booking.home_id = params[:home_id]
    authorize @booking
    @home = Home.find(params[:home_id])
    @booking.status = "Confirmed"
    # For Ranking, DO NOT DELETE!
    if @home.ranking == 'first come first served' || @home.bigger_owners(current_user).empty?
      @booking.save
      redirect_to home_bookings_path, booking_confirmed: 'Your home was successfully booked. TimeSharer wish you a happy stay, and hope to see you again soon. Remember you can see all of your bookings under "Bookings".'
    elsif @booking.valid?
      @booking.status = "Pending"
      bigger_owners = @home.bigger_owners(current_user)
      # iterate the bigger_owners and send them an email or message - to do
      bigger_owner = bigger_owners.each do |owner|
        p owner.name
        p owner.email
        p owner.phone_number
      end
      @booking.save
      redirect_to pending_home_booking_path(@home, @booking)
    else
      render :new
    end
  end

  def pending
    @booking = Booking.find(params[:id])
    authorize @booking
    @home = Home.find(params[:home_id])
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to home_bookings_path(@booking.home), notice: 'Your booking was successfully updated!'
    else
      render :edit
    end
  end

  def approve
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = 'Confirmed'
    @booking.save
    redirect_to home_bookings_home_path(@booking.home)
  end

  def reject
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = 'Rejected'
    @booking.save
    redirect_to home_bookings_home_path(@booking.home)
  end

  def destroy
    home = @booking.home
    @booking.destroy
    redirect_to bookings_path, notice: 'Your booking was successfully deleted!'
  end

  private

  def booking_params
    params.require(:booking).permit(:no_of_guest, :start_date, :end_date, :status)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/views/bookings/_booking_confirmation.html.erb
<div class="modal fade" id="booking-confirmation-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Booking was successful!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= booking_confirmed %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for ([home, booking])  do |f| %>
  <i class="fas fa-plane-departure"></i><%= f.input :start_date, as: :string, input_html: {class: "datepicker"} %>
  <i class="fas fa-plane-arrival"></i><%= f.input :end_date, as: :string, input_html: {class: "datepicker"} %>
  <i class="fas fa-users"></i><%= f.input :no_of_guest, collection: %w[1 2 3 4 5 6 7 8 9 10] %>
  <br>
  <%= f.submit 'Book it Now!', class: "btn btn-info w-100" %>
<% end %>

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>

<%= render 'bookings/form', home: @home, booking: @booking %>

app/views/bookings/home_bookings.html.erb
<div class="image-banner">
  <img class="banner-image-left" src="https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595910044/TimeSharer/copenhagen_interior_5_c0sfot.jpg" alt="vacation home">
  <img class="banner-image-main" src="https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595909712/TimeSharer/copenhagen_interior_4_e091dp.jpg" alt="vacation home">
  <img class="banner-image-right" src="https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595908896/TimeSharer/copenhagen_interior_1_zhn0mt.png">
</div>

<div class="my-bookings">
  <h1><strong>Bookings for <%= @home.home_name %></strong></h1>
  <div class="bookings-table">
    <table class="table">
      <thead>
        <tr>
          <th><i class="fas fa-user"></i>User</th>
          <th><i class="fas fa-plane-arrival"></i>Check in</th>
          <th><i class="fas fa-plane-departure"></i>Check out</th>
          <th><i class="fas fa-moon"></i></i>Nights in total</th>
          <th><i class="fas fa-users"></i>No. of guests</th>
          <th><i class="fas fa-question-circle"></i>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.user.name %></td>
            <td><%= booking.start_date %></td>
            <td><%= booking.end_date %></td>
            <td><%= (booking.end_date - booking.start_date).to_i %></td>
            <td><%= booking.no_of_guest %></td>
            <td><%= booking.status %></td>
            <td>
              <% if booking.ownership.greater_shares_of_ownership?(current_user) && booking.status == 'Pending' %>
                <%= link_to 'Approve', approve_home_booking_path(booking.home, booking), data: { confirm: 'Approve booking?'}, class: 'btn btn-info' %>
                <%= link_to 'Reject', reject_home_booking_path(booking.home, booking), data: { confirm: 'Are you sure to reject?'}, class: "btn btn-outline-secondary" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <div class="text-center">
    <%= link_to 'Return to Overview', home_path(@home), class: 'btn btn-info' %>
  </div>
  <br>
  <br>
</div>

app/views/bookings/index.html.erb
<div class="image-banner">
  <img class="banner-image-left" src="https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595910044/TimeSharer/copenhagen_interior_5_c0sfot.jpg" alt="vacation home">
  <img class="banner-image-main" src="https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595909712/TimeSharer/copenhagen_interior_4_e091dp.jpg" alt="vacation home">
  <img class="banner-image-right" src="https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595908896/TimeSharer/copenhagen_interior_1_zhn0mt.png">
</div>
<div class="my-bookings">
  <h1><strong>My Bookings</strong></h1>
  <div class="bookings-table">
    <table class="table">
      <thead>
        <tr>
          <th><i class="fas fa-home"></i>Home</th>
          <th><i class="fas fa-plane-arrival"></i>Check in</th>
          <th><i class="fas fa-plane-departure"></i>Check out</th>
          <th><i class="fas fa-moon"></i></i>Nights in total</th>
          <th><i class="fas fa-users"></i>No. of guests</th>
          <th><i class="fas fa-question-circle"></i>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.home.home_name %></td>
            <td><%= booking.start_date %></td>
            <td><%= booking.end_date %></td>
            <td><%= (booking.end_date - booking.start_date).to_i %></td>
            <td><%= booking.no_of_guest %></td>
            <td>
              <%= booking.status %>
              <% if booking.ownership.greater_shares_of_ownership?(current_user)  %>
                confirm
              <% end %>
             </td>
            <td>
              <%= link_to 'View', home_path(booking.home), class: 'btn btn-info' %>
              <%= link_to 'Edit', edit_booking_path(booking), class: 'btn btn-outline-info' %>
              <%= link_to 'Delete', booking_path(booking), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-outline-secondary" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div id="map"
     style="width: 90%; height: 600px; margin: 0 auto; border-radius: 6px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/bookings/pending.html.erb
<div class="pending-page">
  <h1><strong>Your booking is pending an approval.</strong></h1>
  <h6>The owners of your vacation home have agreed that all bookings should be approved by one of the owners. Unless you hear from that owner withing the next <strong>48 hours</strong>, your booking has gone through.</h6>
  <%= link_to "View all of your bookings", home_bookings_path(@home) , class: "btn btn-info"%>
</div>