config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :homes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create] do
      member do
        get '/pending', to: 'bookings#pending', as: :pending
        get '/approve', to: 'bookings#approve', as: :approve
        get '/reject', to: 'bookings#reject', as: :reject
      end
    end
    member do
      get '/bookings', to: 'bookings#home_bookings', as: :home_bookings
    end
    resources :notes, only: [:index, :new, :create]
    resources :ownerships, only: [:index]
  end
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :users, only: [:show]
  resources :notes, only: [:index, :new, :create, :destroy]
  resources :ownerships, only: [:edit, :update]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 ts-flash-message" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 ts-flash-message" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if booking_confirmed %>
  <%= render "bookings/booking_confirmation" %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container text-center font-weight-bold">
    <div class="inner-content">
      Copyright © 2020 . Team of TimeSharer
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<!-- Header -->
<header class="">
  <div class="container">
    <div class="d-flex justify-content-between align-items-center">
      <div class="py-10">
        <a class="" href="/"> <h2 class="logo-first">Time<em class="logo-second ">Sharer</em></h2></a>
      </div>

      <div class="py-10 d-none d-sm-block">
        <div class="text-white-menu">
          <div class="d-flex justify-content-between overflow-hidden">
            <% if user_signed_in? %>
              <%= link_to "Homes", homes_path, class: "nav-link text-white-menu-1 text-decoration-none" %>
              <%= link_to "My Bookings", bookings_path, class: "nav-link text-white-menu-2 text-decoration-none" %>
              <%= link_to "Create Home", new_home_path, class: "nav-link text-white-menu-3 text-decoration-none" %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="py-10">
        <button class="navbar-toggler d-none" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-nav ml-auto action-buttons">
          <% if not user_signed_in? %>
            <div class="nav-item dropdown">
				      <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle mr-4">Login</a>
              <div class="dropdown-menu action-form">
                <%= simple_form_for(:user, url: session_path(:user)) do |f| %>
                  <div class="form-group-div" style="margin: 20px; width: 200px">
                    <%= f.input :email,
                                required: false,
                                autofocus: true,
                                placeholder: "Your Email",
                                input_html: { autocomplete: "email" } %>
                    <%= f.input :password,
                                required: false,
                                input_html: { autocomplete: "current-password" } %>
                  </div>
                  <input type="submit" class="btn btn-primary btn-block" value="Login">
                <% end %>
              </div>
			      </div>
			      <div class="nav-item dropdown">
				      <a href="#" data-toggle="dropdown" class="btn btn-primary dropdown-toggle sign-up-btn">Sign up</a>
                <div class="dropdown-menu action-form" style="padding: 20px; width: 300px">
        					<%= render 'devise/registrations/modal' %>
        				</div>
              </div>
          <% else %>

            <div class="">
              <li class="nav-item dropdown">
                <%= image_tag "https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595508571/TimeSharer/stefan_profile_z9orch.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "Homes", homes_path, class: "dropdown-item inline-block d-sm-none" %>
                  <%= link_to "Bookings", bookings_path, class: "dropdown-item inline-block d-sm-none" %>
                  <%= link_to "Create Home", new_home_path, class: "dropdown-item inline-block d-sm-none" %>
                  <div class="border-bottom inline-block d-sm-none" style="width: 90%; margin: 0 auto;"></div>
                  <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </li>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>