config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :homes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create] do
      member do
        get '/pending', to: 'bookings#pending', as: :pending
        get '/approve', to: 'bookings#approve', as: :approve
        get '/reject', to: 'bookings#reject', as: :reject
      end
    end
    member do
      get '/bookings', to: 'bookings#home_bookings', as: :home_bookings
    end
    resources :notes, only: [:index, :new, :create]
    resources :ownerships, only: [:index]
  end
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :users, only: [:show]
  resources :notes, only: [:index, :new, :create, :destroy]
  resources :ownerships, only: [:edit, :update]
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :ownerships, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :users, through: :ownerships

  has_one_attached :photo

  validates :home_name, :country, :address, :maximum_no_of_guest, :ranking, presence: true
  validates :photo, presence: true

  validates :maximum_no_of_guest, :no_of_bed, numericality: { greater_than_or_equal_to: 0 }

  # For ranking by shares of ownerships (2)
  def ownership_for(user)
    ownership = ownerships.find do |o|
      o.user == user
    end
    return ownership
  end

  # For ranking by shares of ownerships
  def bigger_owners(current_user)
    current_user_ownership = ownership_for(current_user)

    bigger_ownerships = ownerships.select do |ownership|
      ownership.shares_of_ownership > current_user_ownership.shares_of_ownership
    end

    bigger_ownerships.map(&:user)
  end

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  accepts_nested_attributes_for :bookings
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @homes = Home.geocoded
    @homes = policy_scope(Home).joins(:ownerships, :users).where("ownerships.user_id = #{current_user.id}").distinct

    @markers = @homes.map do |home|
      {
        lat: home.latitude,
        lng: home.longitude
      }
    end
  end

  def show
    @home = Home.find(params[:id])
    @bookings_json = bookings_json
    @booking = Booking.new
    authorize @home
    @note = Note.new
    @notes = @home.notes.order(created_at: :desc)

    @homes = Home.geocoded
    @markers = [
      {
        lat: @home.latitude,
        lng: @home.longitude
      }
    ]
  end

  def new
    @home = Home.new
    authorize @home
  end

  def create
    @home = Home.new(home_params)
    authorize @home
    if @home.save
      create_ownership
      redirect_to homes_path, notice: 'Your home was successfully created!'
    else
      render :new
    end
  end

  def edit
    @home = Home.find(params[:id])
    authorize @home
  end

  def update
    @home = Home.find(params[:id])
    Home.update(home_params)
    authorize @home
    if @home.save
      create_ownership
      redirect_to home_path(@home), notice: 'Your home was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @home = Home.find(params[:id])
    @home.destroy
    authorize @home
    redirect_to homes_path, notice: 'Your home was successfully deleted!'
  end

  private

  def home_params
    params.require(:home).permit(:country, :city, :address, :maximum_no_of_guest, :no_of_bed, :home_name, :ranking, :photo)
  end

  def event_color(user)
    color = '#065143'
    case user.name
    when 'Stefan' then color = '#e9c46a'
    when 'Billy' then color = '#065143'
    when 'Juljan' then color = '#227c9d'
    when 'Jea' then color = '#f28482'
    end
    return color
  end

  def create_ownership
    @ownership = Ownership.new
    @ownership.user = current_user
    @ownership.is_admin = true
    @ownership.home = @home
    @ownership.shares_of_ownership = params["shares_of_ownership"]
    @ownership.save
  end

  def bookings_json
    hashes = @home.bookings.map do |booking|
      {
        title: booking.user.name,
        start: booking.start_date,
        end: booking.end_date,
        color: event_color(booking.user)
      }
    end
    hashes.to_json
  end
end

app/views/homes/_form.html.erb
<div class="add-home-form">
  <h1><strong>Create Your New Home</strong></h1>
  <br>
  <%= simple_form_for(@home) do |f| %>
    <%= f.input :home_name %>
    <%= f.input :country, as: :country %>
    <%= f.input :city %>
    <%= f.input :address %>
    <%= f.input :maximum_no_of_guest %>
    <!-- Add Javascript for the below form to show up when no.of.bed is more than 6 -->
    <div class="form-group">
      <label for="beds">No. of beds</label>
      <input id="beds" class="form-control" type="number" name="user[no_of_bed]">
    </div>

    <div>
      <%= label_tag "shares_of_ownership" %>
      <br>
      <%= number_field_tag :shares_of_ownership %>
    </div>
    <br>
    <%= f.input :ranking, :collection => %w[first\ come\ first\ served shares\ of\ ownerships], include_blank: false, include_hidden: false, prompt: "Select criteria" %>
    <br>

    <%= f.input :photo, as: :file, required: true %>
    <br>

    <%= f.submit 'Create Home', class: "btn btn-ghost" %>
    <br>
    <br>
  <% end %>
</div>

app/views/homes/edit.html.erb
<h1>Edit your home</h1>
<%= render "form", home: @home %>
<%= link_to "back", home_path(@home), class: "btn btn-gradient" %>
<%= link_to "Delete Home", home_path(@home), method: :delete, class: "btn btn-gradient" %>

app/views/homes/index.html.erb
<style>
  .carousel-item {
    height: 30vh;
    min-height: 350px;
    background: no-repeat center center scroll;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
  }
</style>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <!-- Slide One - Set the background image for this slide in the line below -->
    <div class="carousel-item active" style="background-image: url('https://res.cloudinary.com/dkdlmrgaf/image/upload/v1596116274/TimeSharer/index_2.1_vxdmgf.jpg')"></div>
    <!- Slide Two - Set the background image for this slide in the line below -->
    <div class="carousel-item" style="background-image: url('https://res.cloudinary.com/dkdlmrgaf/image/upload/v1596120107/TimeSharer/index_5.1_ek3ppd.jpg')"></div>
    <!- Slide Three - Set the background image for this slide in the line below -->
    <div class="carousel-item" style="background-image: url('https://res.cloudinary.com/dkdlmrgaf/image/upload/v1596117147/TimeSharer/index_3_stp4sw.jpg')"></div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!-- Banner Ends Here -->

<div class="container-of-cards">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-6">
      <h1><strong>Your vacation homes:</strong></h1>
      <hr>
      <% current_user.homes.each do |home| %>
        <div class="home-cards">
          <%= link_to "", home_path(home), class: "link-spanner" %>
          <div class="home-cards-image">
            <%= cl_image_tag home.photo.key, crop: :fill %>
          </div>
          <div class="home-cards-body">
            <h6><strong><%= home.home_name %></strong></h6>
            <p><i class="fas fa-globe"></i><%= home.country %></p>
            <p><i class="fas fa-map-marker-alt"></i> <%= home.address %>, <%= home.city %></p>
            <p><i class="fas fa-users"></i>Up to <%= home.maximum_no_of_guest %> guests</p>
            <p><i class="fas fa-sort-amount-down"></i>Priority: <%= home.ranking %></p>
          </div>
        </div>
      <% end %>
      <%= link_to new_home_path, class: "create-home-btn btn btn-info" do %>
        <i class="fas fa-plus"></i>Add home
      <% end %>
    </div>
    <div class="col-12 col-md-6 col-lg-6">
      <div
        id="map"
        style="width: 100%; height: 100%;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/homes/new.html.erb
<div class="container" style="margin-top:80px;">
<%= render "form", home: @home %>
<%= link_to "back", homes_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/homes/show.html.erb
<div class="image-banner">
  <img class="banner-image-left" src="https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595910044/TimeSharer/copenhagen_interior_5_c0sfot.jpg" alt="vacation home">
  <img class="banner-image-main" src="https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595909712/TimeSharer/copenhagen_interior_4_e091dp.jpg" alt="vacation home">
  <img class="banner-image-right" src="https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595908896/TimeSharer/copenhagen_interior_1_zhn0mt.png">
</div>

<div class="container">
  <h1 class="booking-header">Make a booking of <%= @home.home_name %></h1>
  <div class="calendar-and-description-box d-flex justify-content-center align-items-center">
    <div class="calendar">
      <div id="bookings-calendar" data-bookings="<%= @bookings_json %>"></div>
    </div>

    <div class="col-xs-12 col-md-4 col-lg-4">
      <div class="">
        <div class="home-show-cards">
          <div class="home-show-cards-image">
            <%= cl_image_tag @home.photo.key, crop: :fill %>
          </div>
          <div class="home-show-cards-body">
            <h4><strong><%= @home.home_name %></strong></h4>
            <hr class="home-cards-hr">
            <p><i class="fas fa-globe"></i><%= @home.country %></p>
            <p><i class="fas fa-map-marker-alt"></i> <%= @home.address %>, <%= @home.city %></p>
            <p><i class="fas fa-users"></i>Up to <%= @home.maximum_no_of_guest %> guests</p>
            <p><i class="fas fa-bed"></i><%= @home.no_of_bed %> beds available</p>
            <p><i class="fas fa-sort-amount-down"></i>Priority: <%= @home.ranking %></p>
            <%= link_to home_ownerships_path(@home), class: "edit-icon" do %>
              <i class="fas fa-user-circle"></i>See owners
            <% end %>
            <%= link_to home_bookings_home_path, class: "search-icon" do %>
              <i class="fas fa-search"></i>Show all bookings
            <% end %>
            <!-- <p><i class="fas fa-edit"></i><%= link_to "Edit home", edit_home_path(@home) %></p> -->



            <div class="home-show-cards-button">
              <!-- Button trigger modal -->
              <div>
                <a href="#" class="btn btn-info w-100" data-toggle="modal" data-target="#booking">Make a booking</a>
              </div>
            </div>


              <!-- Modal -->
              <div class="modal fade" id="booking" tabindex="-1" role="dialog" aria-labelledby="booking" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div class="">
                        <div class="d-flex justify-content-center align-items-center">
                          <div class="" style="width: 400px; margin-bottom: 40px;">
                            <%= render 'bookings/form', home: @home, booking: @booking %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
</div>
<div class="text-center">
  <h1 class="note-header">Notes</h1>
  <div class="d-flex justify-content-center align-items-center">
    <div class="">
      <!-- Button trigger modal -->
      <div class="pl-10">
        <a href="#" class="leave-note-button btn" data-toggle="modal" data-target="#leave">Leave a note<a>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="leave" tabindex="-1" role="dialog" aria-labelledby="leave" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="pr-10">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="">
                <div class="d-flex justify-content-center align-items-center">
                  <div class="" style="width: 400px; margin-bottom: 40px;">
                    <div class="post-form-leave mb-4">
                      <%= image_tag "https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595508571/TimeSharer/stefan_profile_z9orch.jpg", class: "avatar img avatar-note"%>
                      <%= simple_form_for ([@home, @note]), html: { class: "form-inline note-form " } do |f| %>
                      <div class="form-group grow-one">
                        <%= f.input :content, label: false, class: "inpt" %>
                        <%= f.submit 'Comment', class: "btn btn-info note-btn"%>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="notess">
  <% @notes.each do |note| %>
    <div class="note-post mt-3">
      <%= image_tag "https://res.cloudinary.com/dkdlmrgaf/image/upload/v1595508571/TimeSharer/stefan_profile_z9orch.jpg", class: "avatar avatar-note postt"%>
      <div class="note-details">
        <div class="title">
          <div class="username">
            <p><strong><%= note.user.name %></strong></p>
          </div>
          <div class="date">
            <p><%= note.created_at.strftime("%b %e, %l:%M %p") %></p>
          </div>
        </div>
        <hr class="note-hr">
        <div class="content mb-3">
          <p><%= note.content %></p>
        </div>
        <hr class="note-hr">
        <div class="actions">
          <div class="pr-10">
          <%= link_to 'Edit', note_path(note), method: :delete, class: "note-button btn btn-outline-secondary" %>
          </div>
          <%= link_to 'Delete', note_path(note), method: :delete, class: "note-button btn btn-outline-secondary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="container pb-10" style="width: 100%;">
  <div id="map"
    style="width: 100%; height: 300px; border-radius: 4px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>